#!/bin/bash

SCRIPT_FOLDER="$HOME/bin/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
    echo file arlready exists
else
    echo '#!/bin/bash' > $SCRIPT_FILE 
    chmod +x $SCRIPT_FILE
    vim $SCRIPT_FILE
fi


