#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Kupfer.py focus=on
bspc rule -a '*:st' state=floating
bspc rule -a '*:zathura' state=tiled
bspc rule -a '*:emacs' state=tiled

feh --bg-scale ~/img/galaxy.jpg

#set wallpaper and color scheme
#$HOME/bin/scripts/pywal

#start polybar
#$HOME/bin/scripts/polybarstart

#set ctrl + alt + backspace to end xorg server
setxkbmap -option terminate:ctrl_alt_bksp

#remove computer beep
$HOME/bin/scripts/removebeep

